package com.stratocloud.order;

import java.util.Set;

public enum OrderEvent {
    SUBMIT_REQUESTED,
    APPROVE_REQUESTED,
    CONFIRM_REQUESTED,
    REJECT_REQUESTED,
    ROLLBACK_REQUESTED,
    CANCEL_REQUESTED,
    DENY_REQUESTED,


    WORKFLOW_REPORT_JOB_STARTED,
    WORKFLOW_REPORT_JOB_FINISHED,
    WORKFLOW_REPORT_JOB_FAILED,
    WORKFLOW_REPORT_APPROVAL_STARTED,
    WORKFLOW_REPORT_CONFIRM_STARTED,

    WORKFLOW_REPORT_WORKFLOW_FINISHED,
    WORKFLOW_REPORT_WORKFLOW_FAILED, UPDATE_REQUESTED;


    public static final Set<OrderEvent> END_EVENTS = Set.of(
            CANCEL_REQUESTED, DENY_REQUESTED, WORKFLOW_REPORT_WORKFLOW_FINISHED, WORKFLOW_REPORT_WORKFLOW_FAILED
    );

    public static final Set<OrderEvent> APPROVAL_EVENTS = Set.of(
            APPROVE_REQUESTED,
            REJECT_REQUESTED,
            ROLLBACK_REQUESTED,
            DENY_REQUESTED
    );
}
